#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


# LC_ALL=C

# local_branch="$(git rev-parse --abbrev-ref HEAD)"

# valid_branch_regex="^(main|development|master|(features|tests|(bug|hot)fix)(\/[a-zA-Z0-9]+([-_][a-zA-Z0-9]+)*){1,2}|release\/[0-9]+(\.[0-9]+)*(-(alpha|beta|rc)[0-9]*)?)$"

# message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

# if [[ ! $local_branch =~ $valid_branch_regex ]]
# then
#     echo "$message"
#     exit 1
# fi

# npm test && npm lint 
